services:
  - type: web
    name: kintai-system
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 10000
    rootDir: .
    autoDeploy: false
